In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
def get_monthly(df, year, local_area):
    new_df = df[(
        df["Local area"] == local_area
    )]
    new_df["date"] = pd.to_datetime(new_df["date"])
    new_df_year = new_df[new_df["date"].dt.year == year]
    new_df_year["month"] = new_df_year["date"].dt.month

    monthly = (
        new_df_year
        .groupby("month")["request_count"]
        .mean()
    )

    print(monthly)

In [50]:
def get_week(df, year, local_area):
    new_df = df[(
        df["Local area"] == local_area
    )]
    new_df["date"] = pd.to_datetime(new_df["date"])
    new_df_year = new_df[new_df["date"].dt.year == year]
    new_df_year["days_of_week"] = new_df_year["date"].dt.day_name()

    weekly_pattern  = (
        new_df_year
        .groupby("days_of_week")["request_count"]
        .mean()
    )
    pd.set_option('display.max_rows', None)
    print(weekly_pattern)

In [47]:
daily_demand = pd.read_csv("../data/daily_demand.csv")
get_monthly(daily_demand, 2024, "Grandview-Woodland")
get_week(daily_demand, 2024, "Grandview-Woodland")

month
1     35.000000
2     33.862069
3     28.967742
4     35.033333
5     39.451613
6     41.200000
7     42.741935
8     37.290323
9     35.766667
10    34.838710
11    40.633333
12    29.903226
Name: request_count, dtype: float64
days_of_week
Friday       39.153846
Monday       38.547170
Saturday     26.211538
Sunday       18.403846
Thursday     40.269231
Tuesday      44.396226
Wednesday    46.326923
Name: request_count, dtype: float64

/var/folders/f0/cs68sc7504xgdwhqrdm0sx4h0000gn/T/ipykernel_4180/1152526501.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["date"] = pd.to_datetime(new_df["date"])
/var/folders/f0/cs68sc7504xgdwhqrdm0sx4h0000gn/T/ipykernel_4180/1152526501.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_year["month"] = new_df_year["date"].dt.month
/var/folders/f0/cs68sc7504xgdwhqrdm0sx4h0000gn/T/ipykernel_4180/2505959716.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["date"] = pd.to_datetime(new_df["date"])
/var/folders/f0/cs68sc7504xgdwhqrdm0sx4h0000gn/T/ipykernel_4180/2505959716.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_year["days_of_week"] = new_df_year["date"].dt.day_name()

In [ ]:
get_week(daily_demand, 2024, "Grandview-Woodland")

In [ ]:
locations = [
    "Local area",
    "Downtown",                   
    "Kensington-Cedar Cottage",     
    "Kitsilano",                  
    "Renfrew-Collingwood",          
    "Grandview-Woodland",           
    "Mount Pleasant",              
    "Hastings-Sunrise",            
    "Sunset",                       
    "West End",                    
    "Riley Park",                   
    "Fairview",                    
    "Strathcona",                  
    "Victoria-Fraserview",         
    "Dunbar-Southlands",           
    "Marpole",                      
    "Killarney",                    
    "West Point Grey",              
    "Kerrisdale",                
    "Oakridge",                     
    "Arbutus Ridge",               
    "Shaughnessy",                  
    "South Cambie" 
]

In [62]:

get_week(daily_demand, 2023, "Dunbar-Southlands")

days_of_week
Friday       22.250000
Monday       20.634615
Saturday     11.211538
Sunday        9.528302
Thursday     26.500000
Tuesday      26.307692
Wednesday    27.365385
Name: request_count, dtype: float64

/var/folders/f0/cs68sc7504xgdwhqrdm0sx4h0000gn/T/ipykernel_4180/1079571694.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["date"] = pd.to_datetime(new_df["date"])
/var/folders/f0/cs68sc7504xgdwhqrdm0sx4h0000gn/T/ipykernel_4180/1079571694.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_year["days_of_week"] = new_df_year["date"].dt.day_name()

In [8]:
daily_demand = pd.read_csv("../data/daily_demand.csv")

In [9]:
daily_demand = daily_demand.sort_values(
    ["Local area", "date"]
)

In [37]:
daily_demand["lag_1"] = daily_demand.groupby("Local area")["request_count"].shift(1)
daily_demand.tail()

,date,Local area,request_count,lag_1,lag_7,rolling_mean_7,day_of_week,month,weekend
34778,2026-05-10 00:00:00+00:00,West Point Grey,4,19.0,8.0,13.428571,6,5,1
34800,2026-05-11 00:00:00+00:00,West Point Grey,29,4.0,16.0,15.285714,0,5,0
34822,2026-05-12 00:00:00+00:00,West Point Grey,34,29.0,21.0,17.142857,1,5,0
34844,2026-05-13 00:00:00+00:00,West Point Grey,25,34.0,14.0,18.714286,2,5,0
34866,2026-05-14 00:00:00+00:00,West Point Grey,3,25.0,7.0,18.142857,3,5,0

In [19]:
daily_demand["lag_1"] = daily_demand.groupby("Local area")["request_count"].shift(1)
daily_demand.tail(20)

             date       Local area  request_count  lag_1  lag_7
34448  2026-04-25  West Point Grey             10    9.0   11.0
34470  2026-04-26  West Point Grey             11   10.0   12.0
34492  2026-04-27  West Point Grey             25   11.0   16.0
34514  2026-04-28  West Point Grey             19   25.0   17.0
34536  2026-04-29  West Point Grey             16   19.0   18.0
34558  2026-04-30  West Point Grey             19   16.0   13.0
34580  2026-05-01  West Point Grey             17   19.0    9.0
34602  2026-05-02  West Point Grey             11   17.0   10.0
34624  2026-05-03  West Point Grey              8   11.0   11.0
34646  2026-05-04  West Point Grey             16    8.0   25.0
34668  2026-05-05  West Point Grey             21   16.0   19.0
34690  2026-05-06  West Point Grey             14   21.0   16.0
34712  2026-05-07  West Point Grey              7   14.0   19.0
34734  2026-05-08  West Point Grey             13    7.0   17.0
34756  2026-05-09  West Point Grey             19   13.0   11.0
34778  2026-05-10  West Point Grey              4   19.0    8.0
34800  2026-05-11  West Point Grey             29    4.0   16.0
34822  2026-05-12  West Point Grey             34   29.0   21.0
34844  2026-05-13  West Point Grey             25   34.0   14.0
34866  2026-05-14  West Point Grey              3   25.0    7.0

In [21]:
daily_demand["lag_7"] = daily_demand.groupby("Local area")["request_count"].shift(7)
daily_demand.tail(20)

             date       Local area  request_count  lag_1  lag_7
34448  2026-04-25  West Point Grey             10    9.0   11.0
34470  2026-04-26  West Point Grey             11   10.0   12.0
34492  2026-04-27  West Point Grey             25   11.0   16.0
34514  2026-04-28  West Point Grey             19   25.0   17.0
34536  2026-04-29  West Point Grey             16   19.0   18.0
34558  2026-04-30  West Point Grey             19   16.0   13.0
34580  2026-05-01  West Point Grey             17   19.0    9.0
34602  2026-05-02  West Point Grey             11   17.0   10.0
34624  2026-05-03  West Point Grey              8   11.0   11.0
34646  2026-05-04  West Point Grey             16    8.0   25.0
34668  2026-05-05  West Point Grey             21   16.0   19.0
34690  2026-05-06  West Point Grey             14   21.0   16.0
34712  2026-05-07  West Point Grey              7   14.0   19.0
34734  2026-05-08  West Point Grey             13    7.0   17.0
34756  2026-05-09  West Point Grey             19   13.0   11.0
34778  2026-05-10  West Point Grey              4   19.0    8.0
34800  2026-05-11  West Point Grey             29    4.0   16.0
34822  2026-05-12  West Point Grey             34   29.0   21.0
34844  2026-05-13  West Point Grey             25   34.0   14.0
34866  2026-05-14  West Point Grey              3   25.0    7.0

In [22]:
daily_demand["rolling_mean_7"] = daily_demand.groupby("Local area")["request_count"].transform(lambda x: x.rolling(7).mean())
daily_demand.tail()

,date,Local area,request_count,lag_1,lag_7,rolling_mean_7
34778,2026-05-10,West Point Grey,4,19.0,8.0,13.428571
34800,2026-05-11,West Point Grey,29,4.0,16.0,15.285714
34822,2026-05-12,West Point Grey,34,29.0,21.0,17.142857
34844,2026-05-13,West Point Grey,25,34.0,14.0,18.714286
34866,2026-05-14,West Point Grey,3,25.0,7.0,18.142857

In [41]:
daily_demand["date"] = pd.to_datetime(
    daily_demand["date"],
    utc=False
)

In [42]:
daily_demand["day_of_week"] = daily_demand["date"].dt.dayofweek
daily_demand.tail()

,date,Local area,request_count,lag_1,lag_7,rolling_mean_7,day_of_week,month,weekend
34778,2026-05-10,West Point Grey,4,19.0,8.0,13.428571,6,5,1
34800,2026-05-11,West Point Grey,29,4.0,16.0,15.285714,0,5,0
34822,2026-05-12,West Point Grey,34,29.0,21.0,17.142857,1,5,0
34844,2026-05-13,West Point Grey,25,34.0,14.0,18.714286,2,5,0
34866,2026-05-14,West Point Grey,3,25.0,7.0,18.142857,3,5,0

In [43]:
daily_demand["month"] = daily_demand["date"].dt.month
daily_demand.tail()

,date,Local area,request_count,lag_1,lag_7,rolling_mean_7,day_of_week,month,weekend
34778,2026-05-10,West Point Grey,4,19.0,8.0,13.428571,6,5,1
34800,2026-05-11,West Point Grey,29,4.0,16.0,15.285714,0,5,0
34822,2026-05-12,West Point Grey,34,29.0,21.0,17.142857,1,5,0
34844,2026-05-13,West Point Grey,25,34.0,14.0,18.714286,2,5,0
34866,2026-05-14,West Point Grey,3,25.0,7.0,18.142857,3,5,0

In [44]:
daily_demand["weekend"] = (daily_demand["day_of_week"] >= 5).astype(int)
daily_demand.tail()

,date,Local area,request_count,lag_1,lag_7,rolling_mean_7,day_of_week,month,weekend
34778,2026-05-10,West Point Grey,4,19.0,8.0,13.428571,6,5,1
34800,2026-05-11,West Point Grey,29,4.0,16.0,15.285714,0,5,0
34822,2026-05-12,West Point Grey,34,29.0,21.0,17.142857,1,5,0
34844,2026-05-13,West Point Grey,25,34.0,14.0,18.714286,2,5,0
34866,2026-05-14,West Point Grey,3,25.0,7.0,18.142857,3,5,0

In [48]:
daily_demand = daily_demand.dropna()
daily_demand.head()

,date,Local area,request_count,lag_1,lag_7,rolling_mean_7,day_of_week,month,weekend
152,2022-01-08,Arbutus Ridge,26,31.0,2.0,19.428571,5,1,1
174,2022-01-09,Arbutus Ridge,21,26.0,8.0,21.285714,6,1,1
195,2022-01-10,Arbutus Ridge,34,21.0,9.0,24.857143,0,1,0
217,2022-01-11,Arbutus Ridge,54,34.0,21.0,29.571429,1,1,0
239,2022-01-12,Arbutus Ridge,23,54.0,13.0,31.000000,2,1,0

In [51]:
daily_demand["rolling_mean_7"] = daily_demand["rolling_mean_7"].astype(int)
daily_demand["lag_1"] = daily_demand["lag_1"].astype(int)
daily_demand["lag_7"] = daily_demand["lag_7"].astype(int)

In [52]:
# save the new dataset
daily_demand.to_csv(
    "../data/forecasting_dataset.csv",
    index=False
)

In [3]:
daily_demand = pd.read_csv(
     "../data/forecasting_dataset.csv"
)

In [7]:
daily_demand["lag_14"] = daily_demand.groupby("Local area")["request_count"].shift(14)
daily_demand["rolling_mean_30"] = daily_demand.groupby("Local area")["request_count"].transform(lambda x: x.rolling(30).mean())

In [11]:
daily_demand.head()

,date,Local area,request_count,lag_1,lag_7,rolling_mean_7,day_of_week,month,weekend,lag_14,rolling_mean_30
29,2022-02-06,Arbutus Ridge,9,11,9,14,6,2,1,4.0,17.733333
30,2022-02-07,Arbutus Ridge,9,9,22,12,0,2,0,8.0,17.166667
31,2022-02-08,Arbutus Ridge,16,9,14,12,1,2,0,13.0,17.000000
32,2022-02-09,Arbutus Ridge,11,16,8,13,2,2,0,14.0,16.233333
33,2022-02-10,Arbutus Ridge,13,11,17,12,3,2,0,7.0,14.866667

In [10]:
daily_demand = daily_demand.dropna()

In [12]:
# save the new dataset
daily_demand.to_csv(
    "../data/forecasting_dataset.csv",
    index=False
)